---

# Bootsrap server
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:

  - name: install docker
    apt: name=docker.io state=installed

  - name: install docker-py
    pip: name=docker-py

  - name: nginx container
    docker:
      name: my-nginx
      image: jgaspar/my-nginx
      state: started
      ports:
      - "8080:80"
